#!/bin/bash -e

# Absolute path to this script
DIR=$(cd "$(dirname "$0")" ; pwd -P)
# Absolute path to Cross-language dialect's translator
TR=/Volumes/MOE/p/cross-language-dialect/translator
$TR/run/run-java --file=$DIR/entities.yml --out=$DIR/../src/entities.kt
